#!/usr/bin/env python3
"""
Retrieval-augmented reflection (RAG) for the reflect stage
-----------------------------------------------------------
A small, dependency-free knowledge base over the a14y scorecard checks so that reflect.py can
ground its optimization instructions in curated fix recipes and the official a14y docs instead
of relying on the model's memory alone.

Layout (under knowledge/):
  catalog.json   - one entry per check id (name / group / scope / priority / unlocks)
  checks/<id>.md - curated, hand-written fix recipes (frontmatter + body); highest quality
  docs/<id>.md   - official a14y reference per check (generated by fetch_a14y_docs.py)
  examples/      - (future) verified historical success cases for semantic recall

Retrieval is deterministic and keyed by check id, because the a14y check id is a natural primary
key: every fail/warn item maps to exactly one recipe. `retrieve_for_checks` returns the curated
recipe when available, otherwise the crawled docs, otherwise None.
"""

import json
import math
import re
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
KB_DIR = BASE_DIR / "knowledge"
CATALOG_FILE = KB_DIR / "catalog.json"
CHECKS_DIR = KB_DIR / "checks"
DOCS_DIR = KB_DIR / "docs"
EXAMPLES_DIR = KB_DIR / "examples"

_FRONTMATTER_RE = re.compile(r"^---\s*\n.*?\n---\s*\n", re.DOTALL)


def load_catalog() -> dict:
    """Return the check catalog: {id: {name, group, scope, priority, unlocks}}."""
    if CATALOG_FILE.exists():
        try:
            data = json.loads(CATALOG_FILE.read_text(encoding="utf-8"))
            return data.get("checks", {})
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def get_check_meta(check_id: str) -> dict:
    """Catalog metadata for one check id (empty dict when unknown)."""
    return load_catalog().get(check_id, {})


def _strip_frontmatter(text: str) -> str:
    return _FRONTMATTER_RE.sub("", text).strip()


def read_recipe(check_id: str) -> str | None:
    """Return the best available reference for a check id, or None.

    Precedence: curated checks/<id>.md, then crawled docs/<id>.md.
    Frontmatter is stripped so callers get a clean markdown body.
    """
    for directory in (CHECKS_DIR, DOCS_DIR):
        path = directory / f"{check_id}.md"
        if path.exists():
            return _strip_frontmatter(path.read_text(encoding="utf-8"))
    return None


def retrieve_for_checks(checks: list[dict], top_k: int | None = None) -> list[dict]:
    """Return reference chunks for each fail/warn check, keyed by check id.

    Each returned dict: {id, name, group, content}. Checks with no recipe are skipped.
    """
    chunks = []
    for c in checks:
        cid = c.get("id", "")
        content = read_recipe(cid)
        if content:
            chunks.append({
                "id": cid,
                "name": c.get("name", ""),
                "group": c.get("group", ""),
                "content": content,
            })
    return chunks[:top_k] if top_k else chunks


# ---- Lightweight lexical retrieval (for the examples feedback loop, Step 5+) ----
# A tiny BM25 over a list of documents, stdlib only. Used to recall similar historical
# examples; not needed for the deterministic check-id path above.

def _tokenize(text: str) -> list[str]:
    return re.findall(r"[a-z0-9]+", text.lower())


def _bm25_scores(query: str, docs: list[str], k1: float = 1.5, b: float = 0.75) -> list[float]:
    """BM25 scores for `docs` against `query`, with average-document-length normalization."""
    q_terms = _tokenize(query)
    tokenized = [_tokenize(d) for d in docs]
    n = len(tokenized)
    if n == 0 or not q_terms:
        return [0.0] * n

    doc_lens = [len(t) for t in tokenized]
    avg_len = sum(doc_lens) / n

    df: dict[str, int] = {}
    for t in tokenized:
        for term in set(t):
            df[term] = df.get(term, 0) + 1

    idf = {
        term: math.log(1 + (n - df.get(term, 0) + 0.5) / (df.get(term, 0) + 0.5))
        for term in q_terms
    }

    scores: list[float] = []
    for i, t in enumerate(tokenized):
        tf: dict[str, int] = {}
        for term in t:
            tf[term] = tf.get(term, 0) + 1
        score = 0.0
        for term in q_terms:
            f = tf.get(term, 0)
            if not f:
                continue
            denom = f + k1 * (1 - b + b * doc_lens[i] / avg_len)
            score += idf.get(term, 0.0) * (f * (k1 + 1)) / denom
        scores.append(score)
    return scores


def _parse_frontmatter(text: str) -> dict:
    """Best-effort extract of a markdown file's YAML-ish frontmatter into a dict."""
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not m:
        return {}
    fm: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            key, _, value = line.partition(":")
            fm[key.strip()] = value.strip()
    return fm


def rank_examples(query: str, top_k: int = 3, pass_boost: float = 1.5) -> list[dict]:
    """Recall the most relevant historical examples (knowledge/examples/*.md) for `query`.

    Returns [{id, path, content, score, verdict}] sorted by descending BM25 score. Examples
    whose frontmatter marks `verdict: PASS` are multiplied by `pass_boost`, so verified
    successes outrank unverified drafts at equal relevance.
    """
    if not EXAMPLES_DIR.exists():
        return []
    docs: list[tuple[Path, str]] = []
    for path in sorted(EXAMPLES_DIR.glob("*.md")):
        docs.append((path, path.read_text(encoding="utf-8")))
    if not docs:
        return []
    scores = _bm25_scores(query, [d[1] for d in docs])
    ranked: list[dict] = []
    for (path, text), s in zip(docs, scores):
        verdict = _parse_frontmatter(text).get("verdict", "")
        score = s * pass_boost if verdict.upper() == "PASS" else s
        if score > 0:
            ranked.append({
                "id": path.stem,
                "path": str(path),
                "content": text,
                "score": round(score, 4),
                "verdict": verdict,
            })
    ranked.sort(key=lambda r: r["score"], reverse=True)
    return ranked[:top_k]


if __name__ == "__main__":
    from common import console_utf8
    console_utf8()

    catalog = load_catalog()
    print(f"catalog checks: {len(catalog)}")
    curated = list(CHECKS_DIR.glob("*.md")) if CHECKS_DIR.exists() else []
    crawled = list(DOCS_DIR.glob("*.md")) if DOCS_DIR.exists() else []
    print(f"curated recipes: {len(curated)} (knowledge/checks)")
    print(f"crawled docs:    {len(crawled)} (knowledge/docs)")
